using System.Buffers.Binary;
using System.Text;

namespace Terraria.WorldCodec.Tests;

/// <summary>Section-table contract using independently generated bytes, never game worlds.</summary>
public class WorldReaderSectionTableTests
{
    private const int PointerOffset = 26;
    private const int FrameCountOffset = 70;
    private const int PackedBitsOffset = 72;

    // Pointer layout from synthetic vector A in docs/file-format.md.
    private static readonly int[] VectorPointers = [74, 100, 120, 124, 126, 130, 134, 138, 142, 154, 180];

    private static byte[] BuildWorld(short frameCount = 10, byte[]? packedBits = null)
    {
        var packedLength = (frameCount + 7) / 8;
        var headerEnd = PackedBitsOffset + packedLength;
        var bytes = new byte[200 + headerEnd - 74];
        BinaryPrimitives.WriteInt32LittleEndian(bytes, 326);
        Encoding.ASCII.GetBytes("relogic").CopyTo(bytes, 4);
        bytes[11] = 2;
        BinaryPrimitives.WriteUInt32LittleEndian(bytes.AsSpan(12), 1);
        BinaryPrimitives.WriteInt16LittleEndian(bytes.AsSpan(24), 11);
        for (var index = 0; index < VectorPointers.Length; index++)
        {
            WritePointer(bytes, index, VectorPointers[index] + headerEnd - 74);
        }

        BinaryPrimitives.WriteInt16LittleEndian(bytes.AsSpan(FrameCountOffset), frameCount);
        (packedBits ?? [0x38, 0x02]).AsSpan(0, packedLength).CopyTo(bytes.AsSpan(PackedBitsOffset));
        return bytes;
    }

    private static void WritePointer(byte[] bytes, int index, int value) =>
        BinaryPrimitives.WriteInt32LittleEndian(bytes.AsSpan(PointerOffset + (4 * index)), value);

    [Theory]
    [InlineData(10)]
    [InlineData(754)]
    public void ReadSectionTable_SupportedLayout_ReturnsEveryNamedBoundary(short frameCount)
    {
        var bytes = BuildWorld(frameCount, new byte[(frameCount + 7) / 8]);
        using var stream = new MemoryStream(bytes);
        var header = WorldReader.ReadHeader(stream);

        var table = WorldReader.ReadSectionTable(stream, header);

        WorldSectionBoundary[] sections =
        [
            table.FileHeader, table.Metadata, table.Tiles, table.Chests, table.Signs,
            table.NpcsAndMobs, table.TileEntities, table.WeightedPressurePlates,
            table.TownManager, table.Bestiary, table.CreativePowers, table.Footer,
        ];
        var shift = PackedBitsOffset + ((frameCount + 7) / 8) - 74;
        long start = 0;
        for (var index = 0; index < sections.Length; index++)
        {
            var end = index < VectorPointers.Length ? VectorPointers[index] + shift : bytes.Length;
            Assert.Equal(new WorldSectionBoundary(start, end), sections[index]);
            start = end;
        }

        Assert.Equal(frameCount, table.FrameImportant.Count);
    }

    [Theory]
    [InlineData(10, "3802", new int[] { 3, 4, 5, 9 })]
    [InlineData(10, "38FE", new int[] { 3, 4, 5, 9 })]
    [InlineData(16, "8182", new int[] { 0, 7, 9, 15 })]
    [InlineData(0, "", new int[] { })]
    public void ReadSectionTable_PackedFrameFlags_ReturnsOnlyDeclaredBits(short frameCount, string hex, int[] framedTileIds)
    {
        using var stream = new MemoryStream(BuildWorld(frameCount, Convert.FromHexString(hex)));
        var header = WorldReader.ReadHeader(stream);

        var table = WorldReader.ReadSectionTable(stream, header);

        Assert.Equal(frameCount, table.FrameImportant.Count);
        for (var tileId = 0; tileId < frameCount; tileId++)
        {
            Assert.Equal(framedTileIds.Contains(tileId), table.FrameImportant[tileId]);
        }
    }

    [Fact]
    public void ReadSectionTable_754FrameFlags_DecodesFinalTwoTileIdsAndIgnoresPadding()
    {
        var packedBits = new byte[95];
        packedBits[0] = 0x38;
        packedBits[94] = 0xFF;
        using var stream = new MemoryStream(BuildWorld(754, packedBits));
        var header = WorldReader.ReadHeader(stream);

        var table = WorldReader.ReadSectionTable(stream, header);

        Assert.Equal(754, table.FrameImportant.Count);
        Assert.Equal([3, 4, 5, 752, 753], Enumerable.Range(0, 754).Where(id => table.FrameImportant[id]));
    }

    [Theory]
    [InlineData(0, -1)]
    [InlineData(5, -1)]
    [InlineData(10, 4096)]
    [InlineData(0, 25)]
    [InlineData(0, 70)]
    [InlineData(1, 73)]
    [InlineData(3, 110)]
    [InlineData(3, 120)]
    [InlineData(0, 75)]
    [InlineData(10, 195)]
    [InlineData(10, int.MaxValue)]
    public void ReadSectionTable_InvalidPointer_RejectsBeforePayloadOrSeek(int index, int sectionEnd)
    {
        var bytes = BuildWorld();
        WritePointer(bytes, index, sectionEnd);
        using var stream = new TableGuardStream(bytes, payloadStart: 74);
        var header = WorldReader.ReadHeader(stream);

        var error = Assert.Throws<WorldFormatException>(() => WorldReader.ReadSectionTable(stream, header));

        Assert.Equal(WorldFormatError.MalformedSectionTable, error.Error);
        Assert.Equal(0, stream.SeekAttempts);
        Assert.InRange(stream.BytesRead, 26, 74);
    }

    [Fact]
    public void ReadSectionTable_ExactlySixFooterBytes_AcceptsBoundary()
    {
        var bytes = BuildWorld();
        WritePointer(bytes, 10, bytes.Length - 6);
        using var stream = new MemoryStream(bytes);
        var header = WorldReader.ReadHeader(stream);

        var table = WorldReader.ReadSectionTable(stream, header);

        Assert.Equal(new WorldSectionBoundary(194, 200), table.Footer);
    }

    [Theory]
    [InlineData(2147483648L)]
    [InlineData(4294967296L)]
    public void ReadSectionTable_FileAtLeastTwoGiB_RejectsBeforePayloadOrSeek(long fileLength)
    {
        using var stream = new TableGuardStream(BuildWorld(), payloadStart: 74, reportedLength: fileLength);
        var header = WorldReader.ReadHeader(stream);

        var error = Assert.Throws<WorldFormatException>(() => WorldReader.ReadSectionTable(stream, header));

        Assert.Equal(WorldFormatError.MalformedSectionTable, error.Error);
        Assert.Equal(0, stream.SeekAttempts);
        Assert.InRange(stream.BytesRead, 26, 74);
    }

    [Theory]
    [InlineData(-1)]
    [InlineData(0)]
    [InlineData(10)]
    [InlineData(12)]
    [InlineData(short.MaxValue)]
    public void ReadSectionTable_InvalidHeaderSectionCount_RejectsBeforeReadingPointers(short sectionCount)
    {
        using var stream = new TableGuardStream(BuildWorld(), payloadStart: 26);
        var header = WorldReader.ReadHeader(stream) with { SectionCount = sectionCount };

        var error = Assert.Throws<WorldFormatException>(() => WorldReader.ReadSectionTable(stream, header));

        Assert.Equal(WorldFormatError.MalformedSectionTable, error.Error);
        Assert.Equal(24, error.Offset);
        Assert.Equal(26, stream.BytesRead);
        Assert.Equal(0, stream.SeekAttempts);
    }

    public static TheoryData<int> TruncatedTableLengths()
    {
        var lengths = new TheoryData<int>();
        for (var length = PointerOffset; length < 167; length++)
        {
            lengths.Add(length);
        }

        return lengths;
    }

    [Theory]
    [MemberData(nameof(TruncatedTableLengths))]
    public void ReadSectionTable_TruncatedPointersCountOrBits_ThrowsTruncatedAtEndOfData(int length)
    {
        var bytes = BuildWorld(754, new byte[95]).AsSpan(0, length).ToArray();
        using var stream = new TableGuardStream(bytes, payloadStart: 167);
        var header = WorldReader.ReadHeader(stream);

        var error = Assert.Throws<WorldFormatException>(() => WorldReader.ReadSectionTable(stream, header));

        Assert.Equal(WorldFormatError.Truncated, error.Error);
        Assert.Equal(length, error.Offset);
        Assert.Equal(0, stream.SeekAttempts);
        Assert.InRange(stream.BytesRead, 26, length);
    }

    [Fact]
    public void ReadSectionTable_NegativeFrameCount_RejectsBeforePayloadOrSeek()
    {
        var bytes = BuildWorld();
        BinaryPrimitives.WriteInt16LittleEndian(bytes.AsSpan(FrameCountOffset), -1);
        using var stream = new TableGuardStream(bytes, payloadStart: PackedBitsOffset);
        var header = WorldReader.ReadHeader(stream);

        var error = Assert.Throws<WorldFormatException>(() => WorldReader.ReadSectionTable(stream, header));

        Assert.Equal(WorldFormatError.MalformedSectionTable, error.Error);
        Assert.Equal(FrameCountOffset, error.Offset);
        Assert.InRange(stream.BytesRead, 26, PackedBitsOffset);
        Assert.Equal(0, stream.SeekAttempts);
    }

    [Fact]
    public void ReadSectionTable_NonSeekableStream_ThrowsArgumentExceptionWithoutAccessingTable()
    {
        using var stream = new TableGuardStream(BuildWorld(), payloadStart: 26, seekable: false);
        var header = WorldReader.ReadHeader(stream);

        var error = Assert.Throws<ArgumentException>(() => WorldReader.ReadSectionTable(stream, header));

        Assert.Equal("stream", error.ParamName);
        Assert.Equal(26, stream.BytesRead);
        Assert.Equal(0, stream.SeekAttempts);
    }

    [Fact]
    public void ReadSectionTable_ShortReads_StopsAtMetadataAndLeavesStreamOpen()
    {
        using var stream = new TableGuardStream(BuildWorld(), payloadStart: 74);
        var header = WorldReader.ReadHeader(stream);

        WorldReader.ReadSectionTable(stream, header);

        Assert.Equal(74, stream.Position);
        Assert.Equal(74, stream.BytesRead);
        Assert.True(stream.CanRead);
    }

    /// <summary>Detects payload reads/seeks and simulates short reads and large/non-seekable files.</summary>
    private sealed class TableGuardStream(byte[] bytes, int payloadStart, bool seekable = true, long? reportedLength = null) : Stream
    {
        private readonly MemoryStream _inner = new(bytes);

        public long BytesRead { get; private set; }

        public int SeekAttempts { get; private set; }

        public override bool CanRead => _inner.CanRead;

        public override bool CanSeek => seekable;

        public override bool CanWrite => false;

        public override long Length => seekable ? reportedLength ?? _inner.Length : throw new NotSupportedException();

        public override long Position
        {
            get => seekable ? _inner.Position : throw new NotSupportedException();
            set
            {
                SeekAttempts++;
                throw new InvalidOperationException("The table reader must validate without seeking.");
            }
        }

        public override int Read(byte[] buffer, int offset, int count) => Read(buffer.AsSpan(offset, count));

        public override int Read(Span<byte> buffer)
        {
            if (_inner.Position >= payloadStart && !buffer.IsEmpty)
            {
                throw new InvalidOperationException("The table reader entered the world payload.");
            }

            var read = _inner.Read(buffer[..Math.Min(buffer.Length, Math.Min(3, payloadStart - (int)_inner.Position))]);
            BytesRead += read;
            return read;
        }

        public override long Seek(long offset, SeekOrigin origin)
        {
            SeekAttempts++;
            throw new InvalidOperationException("The table reader must validate without seeking.");
        }

        public override void Flush()
        {
        }

        public override void SetLength(long value) => throw new NotSupportedException();

        public override void Write(byte[] buffer, int offset, int count) => throw new NotSupportedException();

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _inner.Dispose();
            }

            base.Dispose(disposing);
        }
    }
}
