import type { ContentRef } from "@studio/world-model";

export type Rgba = readonly [number, number, number, number];

/** A map colour as 0xRRGGBB. */
export type MapColor = number;

/**
 * Terraria's map colours for vanilla content, indexed by content ID. Each ID lists one colour per map option
 * (some content has several, chosen in game by its frame); an empty list means the ID has no map colour.
 * The shipped table is generated by `scripts/map-palette/export.ps1`, see ADR 0002.
 */
export interface MapPalette {
  readonly gameVersion: string;
  readonly tiles: readonly (readonly MapColor[])[];
  readonly walls: readonly (readonly MapColor[])[];
  /** Water, lava, honey, shimmer. */
  readonly liquids: readonly [MapColor, MapColor, MapColor, MapColor];
}

const transparent: Rgba = [0, 0, 0, 0];
const placeholderLiquids: readonly Rgba[] = [
  transparent,
  [40, 110, 230, 255],
  [255, 80, 20, 255],
  [240, 180, 40, 255],
  [180, 100, 240, 255],
];

function rgba(color: MapColor): Rgba {
  return [(color >>> 16) & 0xff, (color >>> 8) & 0xff, color & 0xff, 255];
}

/** A stable, distinguishable colour for content without a map colour (hashed vanilla ID; magenta otherwise). */
export function placeholderColor(ref: ContentRef, layer: "block" | "wall"): Rgba {
  if (ref.kind !== "vanilla") return [255, 0, 255, 255];
  const key = `vanilla:${String(ref.id)}`;
  let hash = 2166136261;
  for (let i = 0; i < key.length; i++) {
    hash = Math.imul(hash ^ key.charCodeAt(i), 16777619) >>> 0;
  }
  const divisor = layer === "wall" ? 2 : 1;
  return [
    Math.floor((64 + (hash & 127)) / divisor),
    Math.floor((64 + ((hash >>> 8) & 127)) / divisor),
    Math.floor((64 + ((hash >>> 16) & 127)) / divisor),
    255,
  ];
}

/**
 * Base colour of a block or wall: the first map option of vanilla content in `mapPalette`, otherwise the placeholder.
 * Frame-dependent options, paint and depth shading are not applied yet.
 */
export function contentColor(ref: ContentRef, layer: "block" | "wall", mapPalette?: MapPalette): Rgba {
  if (ref.kind === "vanilla" && mapPalette !== undefined) {
    const color = (layer === "block" ? mapPalette.tiles : mapPalette.walls)[ref.id]?.[0];
    if (color !== undefined) return rgba(color);
  }
  return placeholderColor(ref, layer);
}

const liquidColorCache = new WeakMap<MapPalette, readonly Rgba[]>();

/** Liquid colours indexed by the CWM liquid kind; kind 0 (no liquid) is transparent. */
export function liquidColors(mapPalette?: MapPalette): readonly Rgba[] {
  if (mapPalette === undefined) return placeholderLiquids;
  let colors = liquidColorCache.get(mapPalette);
  if (colors === undefined) {
    colors = [transparent, ...mapPalette.liquids.map(rgba)];
    liquidColorCache.set(mapPalette, colors);
  }
  return colors;
}
