// Map palette exporter (ADR 0002) against a synthetic assembly; the run against a real installation is opt-in.
import { spawnSync } from "node:child_process";
import { existsSync, mkdtempSync, readFileSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";
import { pathToFileURL } from "node:url";
import { test } from "node:test";
import assert from "node:assert/strict";

const powershell = process.platform === "win32" ? "powershell.exe" : "pwsh";
const available = spawnSync(powershell, ["-NoProfile", "-Command", "$PSVersionTable.PSVersion.Major"]).status === 0;

function runPowerShell(script, args) {
  return spawnSync(powershell, ["-NoProfile", "-NonInteractive", "-ExecutionPolicy", "Bypass", "-File", resolve(script), ...args], {
    encoding: "utf8",
  });
}

async function withTempDirectory(action) {
  const directory = mkdtempSync(join(tmpdir(), "terraria-map-palette-"));
  try {
    await action(directory);
  } finally {
    rmSync(directory, { recursive: true, force: true });
  }
}

/** The generated module is plain TypeScript with erasable types only, so Node can import it directly. */
async function importPalette(file) {
  return (await import(pathToFileURL(file).href)).terrariaMapPalette;
}

test("exports every map option of each content ID as a TypeScript module", { skip: !available && "PowerShell is not installed" }, async () => {
  await withTempDirectory(async (directory) => {
    const result = runPowerShell("scripts/map-palette/fixture-export.ps1", ["-Directory", directory, "-Scenario", "normal"]);
    assert.equal(result.status, 0, result.stderr);
    const file = join(directory, "synthetic-map-palette.ts");
    assert.match(readFileSync(file, "utf8"), /^\/\/ Generated by scripts\/map-palette\/export\.ps1 from Terraria 1\.4\.5\.8\./);
    assert.deepEqual(await importPalette(file), {
      gameVersion: "1.4.5.8",
      tiles: [[0x76583e], [0x6c7078, 0x60666e], [0xe44418], []],
      walls: [[], [0x52565c, 0x2068d2]],
      liquids: [0x2068d2, 0xe44418, 0xdea424, 0x9854d8],
      background: { sky: Array.from({ length: 256 }, (_, i) => (i << 8) | 0xff), dirt: 0x5a3c28, rock: 0x464646, hell: 0x321414 },
      paints: [0xffffff, 0xc80000, 0x0000c8],
    });
    const names = (await import(pathToFileURL(file).href)).terrariaMapNames;
    assert.deepEqual(names, {
      gameVersion: "1.4.5.8",
      tiles: [["Dirt Block"], ["Demon Altar", "Crimson Altar"], ["Grass"], ["Plants"]],
      tileMetadata: [
        { symbols: ["Dirt"], mapOptionCount: 1, nameSources: ["placement"] },
        { symbols: ["DemonAltar"], mapOptionCount: 2, nameSources: ["legend", "legend"] },
        { symbols: ["Grass"], mapOptionCount: 1, nameSources: ["symbol"] },
        { symbols: ["Plants"], mapOptionCount: 0, nameSources: ["symbol"] },
      ],
      walls: [["None"], ["Stone Wall", "Aether \"Crystal\"\nWall"]],
      wallMetadata: [
        { symbols: ["None"], mapOptionCount: 0, nameSources: ["symbol"] },
        { symbols: ["Stone"], mapOptionCount: 2, nameSources: ["placement", "legend"] },
      ],
      liquids: ["Water", "Lava", "Honey", "Shimmer"],
      paints: ["", "Red Paint", "Blue Paint"],
    });
    const coverage = readFileSync(join(directory, "name-coverage.md"), "utf8");
    assert.match(coverage, /\| 2 \| Grass \| terrain \|/);
    assert.match(coverage, /\| 3 \| Plants \| vegetation \|/);
    assert.match(coverage, /Named block IDs: 4\/4/);
  });
});

for (const [scenario, expected] of [
  ["natural-wall", ["Natural Jungle Wall"]],
  ["missing-wall-symbols", []],
  ["ambiguous-wall-symbols", []],
]) {
  test(`wall naming handles ${scenario} while retaining exact existing option labels`, { skip: !available && "PowerShell is not installed" }, async () => {
    await withTempDirectory(async (directory) => {
      const result = runPowerShell("scripts/map-palette/fixture-export.ps1", ["-Directory", directory, "-Scenario", scenario]);
      assert.equal(result.status, 0, result.stderr);
      const names = (await import(pathToFileURL(join(directory, "synthetic-map-palette.ts")).href)).terrariaMapNames;
      assert.deepEqual(names.walls[0], expected);
      assert.deepEqual(names.walls[1], ["Stone Wall", "Aether \"Crystal\"\nWall"]);
      assert.equal(names.wallMetadata[0].mapOptionCount, 0);
    });
  });
}

for (const [scenario, expected, symbols] of [
  ["missing-symbols", [[""], []], [[], []]],
  ["ambiguous-symbols", [[""], ["Plants"]], [["Grass", "MeadowGrass"], ["Plants"]]],
  ["symbol-casing", [["Hallowed Plants 2"], ["UFO Anchor"]], [["HallowedPlants2"], ["UFOAnchor"]]],
]) {
  test(`symbolic naming handles ${scenario} without altering resolved labels`, { skip: !available && "PowerShell is not installed" }, async () => {
    await withTempDirectory(async (directory) => {
      const result = runPowerShell("scripts/map-palette/fixture-export.ps1", ["-Directory", directory, "-Scenario", scenario]);
      assert.equal(result.status, 0, result.stderr);
      const names = (await import(pathToFileURL(join(directory, "synthetic-map-palette.ts")).href)).terrariaMapNames;
      assert.deepEqual(names.tiles.slice(0, 2), [["Dirt Block"], ["Demon Altar", "Crimson Altar"]]);
      assert.deepEqual(names.tiles.slice(2), expected);
      assert.deepEqual(names.tileMetadata.slice(2).map((entry) => entry.symbols), symbols);
      const coverage = readFileSync(join(directory, "name-coverage.md"), "utf8");
      if (scenario === "missing-symbols") assert.match(coverage, /unavailable symbolic metadata/);
      if (scenario === "ambiguous-symbols") assert.match(coverage, /ambiguous symbolic aliases/);
    });
  });
}

for (const scenario of ["invalid-range", "missing-member", "missing-legend", "missing-localization", "item-failure"]) {
  test(`refuses an unsupported contract (${scenario}) without writing output`, { skip: !available && "PowerShell is not installed" }, async () => {
    await withTempDirectory((directory) => {
      const result = runPowerShell("scripts/map-palette/fixture-export.ps1", ["-Directory", directory, "-Scenario", scenario]);
      assert.notEqual(result.status, 0);
      assert.match(result.stderr, /map palette|lookup|contract/i);
      assert.equal(existsSync(join(directory, "synthetic-map-palette.ts")), false);
    });
  });
}

test("exports the palette of a local Terraria installation", {
  skip: !process.env.TERRARIA_ASSEMBLY && "set TERRARIA_ASSEMBLY to a local TerrariaServer.exe to run it",
}, async () => {
  await withTempDirectory(async (directory) => {
    const file = join(directory, "installed-map-palette.ts");
    const result = runPowerShell("scripts/map-palette/export.ps1", ["-TerrariaAssembly", process.env.TERRARIA_ASSEMBLY, "-OutputPath", file]);
    assert.equal(result.status, 0, result.stderr);
    const palette = await importPalette(file);
    assert.ok(palette.tiles.length >= 700);
    assert.ok(palette.walls.length >= 350);
    assert.equal(palette.liquids.length, 4);
    assert.equal(palette.background.sky.length, 256);
    assert.ok(palette.paints.length >= 31);
    const names = (await import(pathToFileURL(file).href)).terrariaMapNames;
    assert.equal(names.gameVersion, palette.gameVersion);
    assert.equal(names.tiles[0][0], "Dirt Block");
    assert.equal(names.tiles[2][0], "Grass");
    assert.equal(names.tiles[3][0], "Plants");
    assert.ok(names.tiles.every((options) => options[0]?.length > 0));
    assert.equal(names.walls[1][0], "Stone Wall");
    assert.equal(names.walls[2][0], "Natural Dirt Wall");
    assert.equal(names.walls[64][0], "Natural Jungle Wall");
    assert.ok(names.walls.every((options) => options[0]?.length > 0));
    assert.deepEqual(names.tiles[26], ["Demon Altar", "Crimson Altar"]);
    assert.deepEqual(names.liquids, ["Water", "Lava", "Honey", "Shimmer"]);
    assert.equal(names.paints[19], "Deep Cyan Paint");
    assert.equal(names.paints[29], "Shadow Paint");
    assert.equal(names.paints[30], "Negative Paint");
    assert.equal(names.paints.length, palette.paints.length);
    assert.deepEqual(names.tiles.map((options) => options.length), palette.tiles.map((options) => Math.max(1, options.length)));
    assert.deepEqual(names.tileMetadata.map((entry) => entry.mapOptionCount), palette.tiles.map((options) => options.length));
    assert.deepEqual(names.walls.map((options) => options.length), palette.walls.map((options) => Math.max(1, options.length)));
    assert.deepEqual(names.wallMetadata.map((entry) => entry.mapOptionCount), palette.walls.map((options) => options.length));
  });
});
