// Map palette exporter (ADR 0002) against a synthetic assembly; the run against a real installation is opt-in.
import { spawnSync } from "node:child_process";
import { existsSync, mkdtempSync, readFileSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";
import { pathToFileURL } from "node:url";
import { test } from "node:test";
import assert from "node:assert/strict";

const powershell = process.platform === "win32" ? "powershell.exe" : "pwsh";
const available = spawnSync(powershell, ["-NoProfile", "-Command", "$PSVersionTable.PSVersion.Major"]).status === 0;

function runPowerShell(script, args) {
  return spawnSync(powershell, ["-NoProfile", "-NonInteractive", "-ExecutionPolicy", "Bypass", "-File", resolve(script), ...args], {
    encoding: "utf8",
  });
}

async function withTempDirectory(action) {
  const directory = mkdtempSync(join(tmpdir(), "terraria-map-palette-"));
  try {
    await action(directory);
  } finally {
    rmSync(directory, { recursive: true, force: true });
  }
}

/** The generated module is plain TypeScript with erasable types only, so Node can import it directly. */
async function importPalette(file) {
  return (await import(pathToFileURL(file).href)).terrariaMapPalette;
}

test("exports every map option of each content ID as a TypeScript module", { skip: !available && "PowerShell is not installed" }, async () => {
  await withTempDirectory(async (directory) => {
    const result = runPowerShell("scripts/map-palette/fixture-export.ps1", ["-Directory", directory, "-Scenario", "normal"]);
    assert.equal(result.status, 0, result.stderr);
    const file = join(directory, "synthetic-map-palette.ts");
    assert.match(readFileSync(file, "utf8"), /^\/\/ Generated by scripts\/map-palette\/export\.ps1 from Terraria 1\.4\.5\.8\./);
    assert.deepEqual(await importPalette(file), {
      gameVersion: "1.4.5.8",
      tiles: [[0x76583e], [0x6c7078, 0x60666e], []],
      walls: [[], [0x52565c]],
      liquids: [0x2068d2, 0xe44418, 0xdea424, 0x9854d8],
      background: { sky: Array.from({ length: 256 }, (_, i) => (i << 8) | 0xff), dirt: 0x5a3c28, rock: 0x464646, hell: 0x321414 },
      paints: [0xffffff, 0xc80000, 0x0000c8],
    });
  });
});

for (const scenario of ["invalid-range", "missing-member"]) {
  test(`refuses an unsupported contract (${scenario}) without writing output`, { skip: !available && "PowerShell is not installed" }, async () => {
    await withTempDirectory((directory) => {
      const result = runPowerShell("scripts/map-palette/fixture-export.ps1", ["-Directory", directory, "-Scenario", scenario]);
      assert.notEqual(result.status, 0);
      assert.match(result.stderr, /map palette|lookup|contract/i);
      assert.equal(existsSync(join(directory, "synthetic-map-palette.ts")), false);
    });
  });
}

test("exports the palette of a local Terraria installation", {
  skip: !process.env.TERRARIA_ASSEMBLY && "set TERRARIA_ASSEMBLY to a local TerrariaServer.exe to run it",
}, async () => {
  await withTempDirectory(async (directory) => {
    const file = join(directory, "installed-map-palette.ts");
    const result = runPowerShell("scripts/map-palette/export.ps1", ["-TerrariaAssembly", process.env.TERRARIA_ASSEMBLY, "-OutputPath", file]);
    assert.equal(result.status, 0, result.stderr);
    const palette = await importPalette(file);
    assert.ok(palette.tiles.length >= 700);
    assert.ok(palette.walls.length >= 350);
    assert.equal(palette.liquids.length, 4);
    assert.equal(palette.background.sky.length, 256);
    assert.ok(palette.paints.length >= 31);
  });
});
